# Generated by Django 2.2 on 2019-12-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191210_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('post', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='news.tags')),
            ],
        ),
    ]
