# Generated by Django 2.2 on 2019-12-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191210_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='posted_by',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
