# Generated by Django 2.2.8 on 2019-12-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191217_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
